services:
  players:
    image: players
    build: 
      context: ./PlayerService
    ports:
      - "5209:5209"
    
  matches:
    image: matches
    build: 
      context: ./MatchService
    ports:
      - "5093:5903"
