# Stage 1 - build
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# copy project file and restore
COPY ["MatchService.csproj", "./"]
RUN dotnet restore "MatchService.csproj"

# copy everything and build
COPY . .
RUN dotnet publish "MatchService.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Stage 2 - runtime
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# expose port 8282 inside the container
EXPOSE 8282

# start the app
ENTRYPOINT ["dotnet", "MatchService.dll"]